## Pengertian NumPy
Disebut Dengan Nama NumPy __(Numeric Python)__. Sebuah Library atau disebut Pustaka Python yang digunakan di hampir semua bidang sains dan teknik. NumPy adalah standar universal untuk bekerja dengan data numerik menggunakan Python, dan merupakan inti dari ekosistem ilmiah Python dan PyData. 
 
API NumPy digunakan secara luas di __Pandas__, __SciPy__, __Matplotlib__, __scikit-learn__, __scikit-image__, dan sebagian besar packages data science dan scientific Python lainnya. Pustaka __NumPy__ berisi larik multidimensi __(multidimensional array)__ dan __struktur data matriks__. NumPy menyediakan _ndarray_, _objek array n-dimensi_ yang homogen, dengan metode untuk mengoperasikannya secara efisien. NumPy dapat digunakan untuk melakukan berbagai operasi matematika pada array. NumPy menambahkan struktur data yang kuat ke Python yang menjamin penghitungan yang efisien dengan array dan matriks dan menyediakan perpustakaan besar fungsi matematika tingkat tinggi yang beroperasi pada array dan matriks ini.

## Penggunaan NumPy
Penggunaan NumPy dapat membuat inisialisasi terlebih dahulu.
```python
import numpy as np
```
Pada penggunaanya numpy dapat digunakan dengan inisialisasi dengan nama _np_.

Beberapa Hal yang dapat dijalankan pada pustaka NumPy
1. NumPy Initialization 
2. Creating Ndarrays in NumPy
3. Add, Remove, and Sort
4. Multi-Dimensional Arrays
5. ndim , shape and size
6. Sorting Array
7. Reshape
8. Convert 1D to 2D
9. Indexing and Slicing
10. Creating Array from Existing Data  
11. Copying
12. Basic array Operation
13. Broadcasting 
14. More Array Operations
15. Save Array into file
16. Latihan Studi Kasus
17. Matrices 
        Create Matrices 
        Matrix Aritmetic 
        Dot Product 
        Matrix Indexing 
        Matrix Aggregation 
        Transposing and Reshaping 
        N-Dimensional Array 
        Flatten N-Dimensional Array 
        Working with math Formulas 

Array NumPy lebih cepat dan lebih ringkas daripada list Python. Sebuah array mengkonsumsi lebih sedikit memori dan jauh lebih nyaman untuk digunakan. NumPy menggunakan lebih sedikit memori untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, yang memungkinkan kode untuk dioptimalkan lebih jauh.

Array adalah grid of values dan berisi informasi tentang data mentah, cara menemukan elemen, dan cara menginterpretasikan elemen. Array memiliki grid elemen yang dapat diindeks dengan berbagai cara. Semua elemen memiliki tipe yang sama, disebut sebagai array _dtype(data type)_. Sebuah array dapat diindeks oleh _tuple_ dari bilangan bulat nonnegatif, dengan _boolean_, oleh array lain, atau dengan bilangan bulat. Rank dari array adalah jumlah dimensi. _Shape_ dari array adalah _tuple_ bilangan bulat yang memberikan ukuran array di setiap dimensi.

### Array
Kalian mungkin sesekali mendengar array yang disebut sebagai "ndarray", yang merupakan singkatan dari "N-dimensional array.". Array berdimensi-N hanyalah array dengan sejumlah dimensi. Kalian mungkin juga mendengar array 1-D, atau array satu dimensi, 2-D, atau array dua dimensi, dan seterusnya. Kelas ndarray NumPy digunakan untuk merepresentasikan matriks dan vektor. Vektor adalah array dengan satu kolom, sedangkan matriks mengacu pada array dengan banyak kolom.
```python
1D array, 2D array, ndarray, vector, matrix
```

#### Pembuatan Array
Sama seperti di objek kontainer Python lainnya, konten array dapat diakses dan dimodifikasi dengan mengindeks atau slicing array. Array yang berbeda bisa berbagi data yang sama, jadi perubahan yang dibuat pada satu array mungkin terlihat di array lain. 

Array attributes mencerminkan informasi intrinsik ke array itu sendiri. Jika kalian perlu mendapatkan, atau bahkan menyetel, properti dari sebuah array tanpa membuat sebuah array baru, kalian sering kali dapat mengakses sebuah array melalui atributnya.
```python
# pembuatan array
np.array()
np.zeros()    
np.ones()     
np.empty()    
np.arange()  
```

In [8]:
# (.numpy()) untuk membuat konten array didalam kurung ([array]).
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
# (.zeros()) untuk membuat konten array dengan nilai 0, dan angka 6 adalah jumlah array
aa = np.zeros(6)
aa

array([0., 0., 0., 0., 0., 0.])

In [11]:
# (.ones()) untuk membuat konten array dengan nilai 1, dan angka 6 adalah jumlah array
a1 = np.ones(6)
a1

array([1., 1., 1., 1., 1., 1.])

```python
# The function empty creates an array whose initial content is random and depends on the state of the memory.
# (.empty()) 6 adalah jumlah array
np.empty(6)
```

In [15]:
# (.arange()) untuk membuat konten nilai dengan menggunakan jangkauan sampai nilai 10 dari nilai 0 dan tiap jangkauannya loncat 2 angka.
print(np.arange(0, 10, 2))  # (start, stop, step)

[0 2 4 6 8]


#### Penambahan, penggolongan dan Pembuangan Array
Beberapa syntax yang sering digunakan dalam NumPy :
```python
np.append()
np.delete()
np.sort()
```

In [9]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# (.append()) untuk menambahkan angka array dari kanan kedalam variabel array
np.append(ar, [5, 6])  # (variabel, data yang yg mau diimput)
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# (.delete()) untuk mengeluarkan angka array
np.append(ar, [1])  # (variabel, angka yang dikeluarkan)
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# (.sort()) untuk untuk mengurutkan angka di data array
np.sort(ar)  # (variabel)
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Ukuran dan Bentuk
Beberapa syntax yang sering digunakan dalam NumPy :
```python
ndarray.ndim()
ndarray.size()
ndarray.shape()
```

In [19]:
import numpy as np
# contoh
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
                         
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [20]:
# (.ndim()) untuk menampilkan jumlah axes atau dimensi dari array.
array_example.ndim

3

In [21]:
# (.size()) untuk menampilkan jumlah total elemen pada erray.
array_example.size

24

In [23]:
# (.shape()) untuk menampilkan properties dari array (dimensi, baris, colomn)
array_example.shape

(3, 2, 4)

###### Reshape
Digunakan untuk memberikan bentuk baru ke array tanpa mengubah datanya. Ingatlah bahwa ketika kalian menggunakan metode reshape, array yang ingin kalian hasilkan harus memiliki jumlah elemen yang sama dengan array asli. Jika kalian memulai dengan sebuah array dengan 12 elemen, kalian harus memastikan bahwa array baru kalian juga memiliki total 12 elemen.
```python
np.reshape()
```

In [27]:
# misalkan kalian punya array 1 dimensi dengan jumlah 6
er = np.arange(6)
er

array([0, 1, 2, 3, 4, 5])

In [26]:
# dengan menggunakan reshape array akan dikembalikan dan diubah bentuknya kedalam variabel baru yang kalian inginkan
ber = er.reshape(3, 2)
ber

array([[0, 1],
       [2, 3],
       [4, 5]])

Bentuk _Reshape_ dengan parameter
```python
np.reshape(var, newshape, order)
```
var      = variabel yang akan diambil datanya

newshape = bentuk baru yang akan diinginkan.

order    = _'C'_ read/write elemen menggunakan C-like index order, _'F'_ read/write elemen menggunakan fortran-like index order, _'A'_ berarti read/write elemen dengan Fortran-like index order. 

###### Mengubah 1D menjadi 2D
Biasanya menggunakan perintah 2 perintah dibawah ini.
```python
np.newaxis
np.expand_dims
```

In [32]:
# (.newaxis) untuk mengembalikan nilai array menjadi bentuk array 2 dimensi
er2 = er[np.newaxis]
print(er2)
print(er2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [38]:
# (.newaxis) untuk mengembalikan nilai array menjadi bentuk array 2 dimensi dengan baris 0-6
er3 = er[:, np.newaxis]
print(er3)
print(er3.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [37]:
# (.expand_dims()) untuk mengembalikan nilai array menjadi bentuk array 2 dimensi dengan baris 0-6
er4 = np.expand_dims(er, axis=0)
print(er4)
print(er4.shape)

[[0 1 2 3 4 5]]
(1, 6)


#### Indexing and Slicing
Penggunaan Slicing dan Indexing di array.

Kalian mungkin ingin mengambil bagian dari array atau elemen array tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. Untuk melakukannya, kalian perlu membuat subset, memotong, dan / atau mengindeks array kalian.


In [39]:
# contoh
aerr = np.array([[1, 2, 3, 4], [5, 6, 7, 8, ], [9, 10, 11, 12]])
aerr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
print(aerr[aerr>=5])
print(aerr[aerr%2==0])
print(aerr[(aerr>2)&(aerr<11)])
print(aerr[0:2])
print(aerr[1:])

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


##### Creating Array from Existing Data
Pembuatan array baru dari data yang ada. Secara umum perintah yang sering digunakan ada 5 :
```python
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()
```

In [42]:
irr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [45]:
# mengembalikan array irra dari baris ke 4 sampai baris ke 8
irr1 = irr[3:8]
irr1

array([4, 5, 6, 7, 8])

In [49]:
# contoh menumpuk dua array
a_1 = np.array([[1, 1],
               [2, 2]])

a_2 = np.array([[3, 3],
               [4, 4]])

In [53]:
# (.vstack()) untuk menumpuk dua array vertikal dari arra a_1 dan a_2 
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [54]:
# (.vstack()) untuk menumpuk dua array horizontal dari arra a_1 dan a_2 
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
# contoh membagi array menjadi beberapa array yang lebih kecil
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [
                    13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
# (.hsplit()) untuk membagi variabel arrsplit menjadi 3 bagian
np.hsplit(arrsplit, 3) # (var, jumlah array yang akan dibagi)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [58]:
# (.view()) untuk melihat objek yang baru dari array arrsplit1
arrsplit1 = arrsplit.view()
arrsplit1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
# (.copy()) untuk menyalin salinan lengkap dari array dan datanya (salinan dalam).
arrsplit21 = arrsplit1.copy()
arrsplit21

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

#### Basic Operation 
Numpy juga memberi dukungan untuk penggunanya dapat menggunakan operasional basic seperti _+,-,/, dan lain lain_.

In [71]:
# (.sum()) untuk menjumlahkan angka array a
# (axis=1) untuk menjumlahkan objek angka di ndarray arrsplit
print(a.sum())
print(arrsplit.sum(axis=0))

6
[14 16 18 20 22 24 26 28 30 32 34 36]


In [72]:
a_1 + a_2

array([[4, 4],
       [6, 6]])

In [73]:
a_1 * a_2

array([[3, 3],
       [8, 8]])

##### Broadcasting
Broadcasting adalah mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda. Dimensi array kalian harus kompatibel, misalnya, jika dimensi kedua array sama atau salah satunya adalah 1. Jika dimensinya tidak kompatibel, kalian akan mendapatkan value error.

Operasi ini memungkinkan array dapat dioperasikan menggunakan dengan satu bilangan (atau disebut ooerasi antar vevektor dan skalar) atau antara array dengan dua ukuran berbeda. 

Misalnya, array kalian (kita menyebutnya "data") mungkin berisi informasi tentang jarak dalam mil tetapi Anda ingin mengonversi informasi menjadi kilometer. Kalian dapat melakukan operasi ini dengan:


In [74]:
a * 1.6

array([1.6, 3.2, 4.8])

##### More array Operation
Pada operasi ini NumPy melakukan fungsi agregasi. Selain _min_, _max_, dan _sum_, kalian bisa dengan mudah menjalankan _mean_ untuk mendapatkan rata-rata, _prod_ untuk mendapatkan hasil perkalian elemen, _std_ untuk mendapatkan standard deviation, dan banyak lagi.
```python
var.max()
var.min()
var.sum()
```
      Maximum, minimum, sum, mean, product, standard deviation, and more
      
Secara default, setiap fungsi agregasi NumPy akan mengembalikan agregat dari seluruh array.

In [76]:
arrsplit.sum()

300

In [77]:
arrsplit.min(axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
arrsplit.std()

6.922186552431729

### Matrix
Pada matriks juga sama dengan pengunaan motede array diatas seperti _.ones()_, _zeros()_, dan _random.random()_.

In [79]:
print(np.random.random((3, 2)))

[[0.59275014 0.87120247]
 [0.68066907 0.40685935]
 [0.52419567 0.6027321 ]]


### Matrix Artihmetic
Pengoperasian Matrix dapat melakukan penjumlahan dan perkalian matrix dengan mengunakan operator aritmatika _(+-*/)_.

In [83]:
daterr = np.array([[1, 2], [3, 4]])
ones = np.ones([2, 2])
print(daterr)

[[1 2]
 [3 4]]


In [84]:
print(daterr+ones)

[[2. 3.]
 [4. 5.]]


#### Dot Product
Pada matode matriks _dot()_ dapat digunakan untuk menjalankan operasi dot product dengan matriks lain.

In [85]:
a_11 = np.array([[1, 2, 3], [4, 5, 6]]) 
a_22 = np.array([[7, 8], [9, 10], [11, 12]])

In [86]:
print(np.dot(a_11, a_22))

[[ 58  64]
 [139 154]]


### Matrix Indexing & Aggragation
Matrix dapat melakukan operasi indexing, slicing dann penjumlahan untuk memanipulasi matriks.
```python
# indexing dan Slicing
print(data[2]) 
print(data[0,1]) 
print(data[1:3]) 
print(data[0:2,1])
# operasi penjumlahan
print(data.max()) 
print(data.min()) 
print(data.sum())
```

#### Transposing and Reshaping
Kebutuhan umum saat menangani matriks adalah kebutuhan untuk rotate. Hal ini sering terjadi ketika kita perlu melakukan dot product dari dua matriks dan perlu menyelaraskan dimensi mereka. Array NumPy memiliki properti yang disebut T untuk mendapatkan transpos dari sebuah matriks.


In [87]:
print(a_22.T)

[[ 7  9 11]
 [ 8 10 12]]


Dalam kasus penggunaan yang lebih lanjut, kalian mungkin perlu mengganti dimensi matriks tertentu. Ini sering terjadi dalam aplikasi machine learning di mana model tertentu mengharapkan bentuk tertentu untuk masukan yang berbeda dari kumpulan data kalian. 

Metode _reshape()_ NumPy berguna dalam kasus ini. Kalian hanya memberikan dimensi baru yang kalian inginkan untuk matriks. Kalian dapat meneruskan -1 untuk dimensi dan NumPy dapat menyimpulkan dimensi yang benar berdasarkan matriks Anda


In [88]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [89]:
print(data_col.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


Matriks juga dapat menggunakan _np.transpose()_ untuk membalikkan atau mengubah axes array sesuai dengan nilai yang kalian tentukan. Jika kalian mulai dengan array ini.

In [91]:
marr = np.arange(6).reshape((2, 3)) 
print(marr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array
NumPy dapat melakukan semua yang telah kita sebutkan dalam berbagai dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

In [92]:
ndarr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Flatten N-Dimensional Array 
Ada dua cara populer untuk meratakan array: _.flatten()_ dan _.ravel()_. Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan _.ravel()_ sebenarnya merupakan referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan memengaruhi array induk juga. Karena ravel tidak membuat salinan, ini menghemat memori.

In [93]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
print(arrflat.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Membuat Rumus matetamtika dalam NumPy
Misalnya, ini adalah rumus mean square error (rumus utama yang digunakan dalam __supervised machine learning model__ yang menangani regresi):
```python
error = (1/n) * np.sum(np.square(observed - prediction))
```

In [95]:
print(np.__doc__) ## melihat dari doc string modul / libray numpy 


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl